[versions]
junit = "5.10.1"

[libraries]
jena = { module = "org.apache.jena:apache-jena-libs", version = "4.1.0" }
junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
wldt = { module = "io.github.wldt:wldt-core", version = "0.2.1" }
wot-servient = { module = "io.github.sane-city:wot-servient", version = "1.16-SNAPSHOT" }

[bundles]
java-testing = [ "junit-api" ]

[plugins]
java-qa = { id = "org.danilopianini.gradle-java-qa", version = "1.29.0"}
publish-on-central = { id = "org.danilopianini.publish-on-central", version = "5.0.20" }
