openapi: 3.0.0
servers:
  - description: WoDT Digital Twin API - WLDT Framework implementation
    url: http://localhost:<port>
info:
  description: This is the API of exposed by the WoDT Digital Twin
  version: 1.0.0
  title: WoDT Digital Twin API - WLDT Framework implementation
  contact:
    email: andrea.giulianelli7@unibo.it
  license:
    name: Apache 2.0 License
    url: 'https://www.apache.org/licenses/LICENSE-2.0'

tags:
  - name: WoDT Digital Twin Interface API
    description: This is the API exposed by the WoDT Digital Twin Interface for Consumers.

paths:
  /dtkg:
    get:
      tags:
        - WoDT Digital Twin Interface API
      summary: obtain the current Digital Twin Knowledge Graph
      operationId: getDigitalTwinKnowledgeGraph
      description: obtain the current Digital Twin Knowledge Graph
      responses:
        '200':
          description: the Digital Twin Knowledge Graph
          content:
            text/turtle:
              schema:
                type: string
                example: |
                  <http://localhost:3000/>
                    <https://lampontology.com/ontology#isOn>
                            false;
                    <https://lampontology/ontology#isLocatedInside>
                            <http://example.com/house>;
                    <https://purl.org/wodt/availableActionId>
                            "switch-action-key" .
        

        '204':
          description: the current Digital Twin Knowledge Graph is empty

  /dtd:
    get:
      tags:
        - WoDT Digital Twin Interface API
      summary: obtain the current Digital Twin Description of the WoDT Digital Twin
      operationId: getDigitalTwinDescription
      description: obtain the current Digital Twin Description of the WoDT Digital Twin
      responses:
        '200':
          description: the Digital Twin Description
          content:
            application/td+json:
              schema:
                example: |
                  {
                      "@context": "https://www.w3.org/2022/wot/td/v1.1",
                      "id": "http://localhost:3000",
                      "@type": "https://lampontology.com/ontology#Lamp",
                      "version": {
                          "instance": "1.2.3",
                          "model": "1.0.0"
                      },
                      "https://purl.org/wodt/physicalAssetId": "lampPA",
                      "securityDefinitions": {
                          "nosec_sc": {
                              "scheme": "nosec"
                          }
                      },
                      "security": "nosec_sc",
                      "properties": {
                          "availableActions": {
                              "@type": "https://purl.org/wodt/AvailableActions",
                              "readOnly": true
                          },
                          "is-on-property-key": {
                              "https://purl.org/wodt/domainTag": "https://lampontology.com/ontology#isOn",
                              "https://purl.org/wodt/augmentedInteraction": false,
                              "readOnly": true
                          },
                          "located-inside": {
                              "https://purl.org/wodt/domainTag": "https://lampontology/ontology#isLocatedInside",
                              "readOnly": true
                          }
                      },
                      "actions": {
                          "switch-action-key": {
                              "https://purl.org/wodt/domainTag": "https://lampontology.com/ontology#SwitchCommand",
                              "https://purl.org/wodt/augmentedInteraction": false,
                              "forms": [
                                  {
                                      "href": "http://localhost:3000/action/switch-action-key"
                                  }
                              ]
                          }
                      },
                      "forms": [
                          {
                              "href": "ws://localhost:3000/dtkg",
                              "subprotocol": "websocket",
                              "op": "observeallproperties"
                          }
                      ],
                      "links": [
                          {
                              "href": "https://raw.githubusercontent.com/Web-of-Digital-Twins/dtd-conceptual-model/refs/heads/main/implementations/wot/dtd-thing-model.tm.jsonld",
                              "rel": "type",
                              "type": "application/tm+json"
                          },
                          {
                              "href": "http://localhost:3000/dtkg",
                              "rel": "https://purl.org/wodt/dtkg"
                          }
                      ]
                  }
        '204':
          description: the current Digital Twin Description is empty

  /action/{actionName}:
    post:
      tags:
        - WoDT Digital Twin Interface API
      summary: request the execution of an action to the WoDT Digital Twin
      operationId: invokeAction
      description: request the execution of an action to the WoDT Digital Twin
      parameters:
        - in: path
          name: actionName
          description: the id of the action to invoke
          example: switch-action-key
          required: true
          schema:
            type: string
      responses:
        '202':
          description: the action invocation has been elaborated by the WoDT Digital Twin
        '400':
          description: invalid action id provided or action currently not available
